export const v14Endpoints = {
  webhooks: "/v1/webhooks",
  webhook_detail: "/v1/webhooks/{webhook_id}",

  settings: "/v1/settings",
  settings_checkout: "/v1/settings/checkout",
  settings_orders: "/v1/settings/orders",
  settings_users: "/v1/settings/users",
  settings_tax: "/v1/settings/tax",
  settings_payments: "/v1/settings/payments",
  settings_products: "/v1/settings/products",
  settings_promotions: "/v1/settings/promotions",
  settings_shop: "/v1/settings/shop",
  settings_pos: "/v1/settings/pos",
  settings_product_review: "/v1/settings/product_review",
  settings_theme: "/v1/settings/theme",
  settings_theme_draft: "/v1/settings/theme/draft",
  settings_layouts: "/v1/settings/layouts",
  settings_layouts_draft: "/v1/settings/layouts/draft",
  settings_domains: "/v1/settings/domains",
  settings_third_party_ads: "/v1/settings/third_party_ads",
  settings_theme_publish: "/v1/settings/theme/publish",
  settings_layouts_publish: "/v1/settings/layouts/publish",

  sale_products: "/v1/sales/{sale_id}/products",
  sale_product_status: "/v1/sales/{sale_id}/products/{sale_product_id}/status",
  sale_products_delete: "/v1/sales/{sale_id}/delete_products",
  sale_comments: "/v1/sales/{sale_id}/comments",
  sale_customers: "/v1/sales/{sale_id}/customers",

  user_coupons: "/v1/user_coupons",
  user_coupons_cursor: "/v1/user_coupons/list",
  user_coupon_claim: "/v1/user_coupons/{coupon_code}/claim",
  user_coupon_redeem: "/v1/user_coupons/{coupon_code}/redeem",

  wish_list_items: "/v1/wish_list_items",

  staffs: "/v1/staffs",
  staff_detail: "/v1/staffs/{staff_id}",

  return_order_inspection: "/v1/return_orders/{return_order_id}/inspection",
  return_order_delivery_status_v14: "/v1/return_orders/{return_order_id}/return_order_delivery_status",
  return_order_message: "/v1/return_orders/{return_order_id}/messages",
  purchase_order_update: "/v1/pos/purchase_orders/{purchase_order_id}",
  purchase_order_child: "/v1/pos/purchase_orders/{purchase_order_id}/child",
  purchase_orders_bulk_delete: "/v1/pos/purchase_orders/bulk_delete",

  product_promotions: "/v1/products/{product_id}/promotions",
  coupon_center_promotions: "/v1/promotions/coupon-center",
  customer_coupon_promotions: "/v1/customers/{customer_id}/coupon_promotions",

  merchant_app_metafields: "/v1/merchants/current/app_metafields",
  merchant_app_metafield_detail: "/v1/merchants/current/app_metafields/{metafield_id}",
  merchant_app_metafields_bulk: "/v1/merchants/current/app_metafields/bulk",
  merchant_metafields: "/v1/merchants/current/metafields",
  merchant_metafield_detail: "/v1/merchants/current/metafields/{metafield_id}",
  merchant_metafields_bulk: "/v1/merchants/current/metafields/bulk",

  product_app_metafields: "/v1/products/{product_id}/app_metafields",
  product_app_metafield_detail: "/v1/products/{product_id}/app_metafields/{metafield_id}",
  product_app_metafields_bulk: "/v1/products/{product_id}/app_metafields/bulk",
  product_metafields: "/v1/products/{product_id}/metafields",
  product_metafield_detail: "/v1/products/{product_id}/metafields/{metafield_id}",
  product_metafields_bulk: "/v1/products/{product_id}/metafields/bulk",
  product_metafield_definition: "/v1/metafield_definitions/products/{metafield_definition_id}",

  order_app_metafields: "/v1/orders/{order_id}/app_metafields",
  order_app_metafield_detail: "/v1/orders/{order_id}/app_metafields/{metafield_id}",
  order_app_metafields_bulk: "/v1/orders/{order_id}/app_metafields/bulk",
  order_metafields: "/v1/orders/{order_id}/metafields",
  order_metafield_detail: "/v1/orders/{order_id}/metafields/{metafield_id}",
  order_metafields_bulk: "/v1/orders/{order_id}/metafields/bulk",

  customer_app_metafields: "/v1/customers/{customer_id}/app_metafields",
  customer_app_metafield_detail: "/v1/customers/{customer_id}/app_metafields/{metafield_id}",
  customer_app_metafields_bulk: "/v1/customers/{customer_id}/app_metafields/bulk",
  customer_metafields: "/v1/customers/{customer_id}/metafields",
  customer_metafield_detail: "/v1/customers/{customer_id}/metafields/{metafield_id}",
  customer_metafields_bulk: "/v1/customers/{customer_id}/metafields/bulk",

  order_item_app_metafields: "/v1/orders/{order_id}/items/app_metafields",
  order_item_app_metafields_bulk: "/v1/orders/{order_id}/items/app_metafields/bulk",
  order_item_metafields: "/v1/orders/{order_id}/items/metafields",
  order_item_metafields_bulk: "/v1/orders/{order_id}/items/metafields/bulk",
} as const;
